# .github/workflows/pushimagetogithub.yml
name: pushimagetogithub.yml

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      env:
        DOCKERHUB_REPOSITORY: your-dockerhub-username/hello-world
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build --platform linux/amd64 -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
